# Generated by Django 3.2.6 on 2021-08-16 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0003_alter_todolist_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='deadline',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
