# Generated by Django 3.2.6 on 2021-08-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0004_alter_todolist_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(default='My Tasks', max_length=1024, null=True),
        ),
    ]
